name: CI (shallow)
on:
  pull_request:
    paths-ignore:
      - README.md
      - .gitignore
      - Documentation/**
jobs:
  auto-cancel:
    runs-on: ubuntu-latest
    steps:
    - uses: technote-space/auto-cancel-redundant-job@v1
  test-linux:
    needs: verify-generated-linuxmain
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: find -name XCTestManifests.swift -o -name LinuxMain.swift | xargs rm
    # ^^ or fails due to some tests not being done for newer Swifts
    - run: swift test -Xswiftc -warnings-as-errors
  test-macos:
    needs: auto-cancel
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        project: PromiseKit.xcodeproj
        scheme: PromiseKit
        destination: platform=macOS
        action: build
        build-settings: SWIFT_TREAT_WARNINGS_AS_ERRORS=YES
    - uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        project: PromiseKit.xcodeproj
        scheme: PromiseKit
        destination: platform=macOS
        action: test
        enable-code-coverage: true
    - uses: codecov/codecov-action@v1
  verify-generated-linuxmain:
    runs-on: macos-latest
    needs: auto-cancel
    steps:
    - uses: actions/checkout@v2
    - run: swift test --generate-linuxmain
    - run: git diff --exit-code
