name: CI (exhaustive)
on: workflow_dispatch
jobs:
  auto-cancel:
    runs-on: ubuntu-latest
    steps:
    - uses: technote-space/auto-cancel-redundant-job@v1

  build-linux:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        swift:
        - 4.0.3
        - 4.1.3
        - 4.2.4
        - 5.0.3
        - 5.1.5
        - 5.2.5
        - 5.3.3
        - 5.4.0
    container:
      image: swift:${{ matrix.swift }}
    steps:
    - uses: actions/checkout@v2
    - run: |
        if [ ${v:0:1} == 4 ]; then
          echo "VERSIONS=3 4" >> $GITHUB_ENV
        else
          echo "VERSIONS=4 4.2 5" >> $GITHUB_ENV
        fi
      shell: bash
      env:
        v: ${{ matrix.swift }}
    - run: |
        for v in $VERSIONS; do
          swift build -Xswiftc -warnings-as-errors -Xswiftc -swift-version -Xswiftc $v
        done

  test:
    runs-on: macos-latest
    strategy:
      matrix:
        dst:
        - platform=macOS
        - platform=tvOS Simulator,OS=14.3,name=Apple TV
        - platform=iOS Simulator,OS=14.4,name=iPhone 12
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ^12
    - uses: actions/checkout@v2
    - uses: sersoft-gmbh/xcodebuild-action@v1
      with:
        project: PromiseKit.xcodeproj
        scheme: PromiseKit
        destination: ${{ matrix.dst }}
        action: test
        enable-code-coverage: true
    - uses: codecov/codecov-action@v1

  carthage:
    runs-on: macos-10.15
    strategy:
      matrix:
        xcode: [^10, ^11, ^12]
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}
    - uses: actions/checkout@v2

    - uses: mingjun97/file-regex-replace@v1
      with:
        regex: SWIFT_TREAT_WARNINGS_AS_ERRORS = NO
        replacement: SWIFT_TREAT_WARNINGS_AS_ERRORS = YES
        include: project.pbxproj

    - run: |
        if [ ${{ matrix.xcode }} == ^12 ]; then
          echo "CARTHAGE_ARGS=--use-xcframeworks" >> $GITHUB_ENV
        fi
    - run: carthage build --no-skip-current --no-use-binaries $CARTHAGE_ARGS

  lint:
    runs-on: macos-10.15
    strategy:
      matrix:
        xcode:
          - ^10
          - ^11
          - ^12
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{ matrix.xcode }}
    - uses: actions/checkout@v2
      with:
        submodules: true
    - run: pod lib lint --fail-fast
